# Generated by Django 5.2.9 on 2026-02-14 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(help_text='ИНН поставщика (10 цифр для юр.лиц, 12 цифр для ИП)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 цифр (для юр.лиц) или 12 цифр (для ИП)', regex='^\\d{10}|\\d{12}$')]),
        ),
    ]
