"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rbud4tf*o7%b8-q8o1r3f4zjtr_%!xk5z&o6e!wlh00b$0t%6d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rest_passwordreset',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular', 
    'celery',
    'backend.apps.BackendConfig',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orders.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True
DATE_INPUT_FORMATS =  ['%d-%m-%Y', ]
DATE_FORMAT = 'd-m-Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL="backend.User"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',          # 100 запросов в час для анонимов
        'user': '1000/hour',         # 1000 запросов в час для пользователей
        'login': '5/minute',         # 5 запросов в минуту для входа
        'register': '10/hour',       # 10 запросов в час для регистрации
        'product_list': '60/minute', # 60 запросов в минуту для списка товаров
        'order_create': '20/hour',   # 20 запросов в час для создания заказов
    },
       
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    
    
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Orders API',
    'DESCRIPTION': '''
    API для автоматизации закупок в розничной сети.
    
    ## Основные возможности
    
    - **Регистрация и аутентификация** пользователей (клиентов и поставщиков)
    - **Управление товарами** - создание, редактирование, импорт из разных форматов
    - **Оформление заказов** - заказы с товарами от разных поставщиков
    - **Управление заказами** - подтверждение, отмена, статистика
    - **Импорт товаров** - поддержка CSV, JSON, YAML форматов
    
    ## Аутентификация
    
    Для доступа к защищённым эндпоинтам требуется JWT токен.
    
    1. Получите токен: `POST /api/token/`
    2. Используйте в заголовке: `Authorization: Bearer <access_token>`
    
    ## Типы пользователей
    
    - **Клиент (client)** - делает закупки по каталогу
    - **Поставщик (supplier)** - управляет товарами и обрабатывает заказы
    
    ## Контакты
    
    - **Поддержка**: support@orders.com
    - **Версия API**: 1.0.0
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    
    # Настройки схемы
    'SCHEMA_PATH_PREFIX': r'/api/',
    
    # Кастомизация типов
    'ENUM_NAME_OVERRIDES': {
        'UserTypeEnum': 'backend.models.User.USER_TYPE_CHOICES',
        'OrderStatusEnum': 'backend.models.Order.STATUS_CHOICES',
    },
    
    # Скрыть некоторые поля из документации
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
}

# Redis Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # База данных 1 для кэша
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PARSER_CLASS': 'redis.connection.HiredisParser',  # Опционально, для ускорения
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            }
        },
        'KEY_PREFIX': 'purchasing_system',  # Префикс для всех ключей
        'TIMEOUT': 60 * 15,  # 15 минут по умолчанию
    },
    'session': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',  # База данных 2 для сессий
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'session',
    }
}

# Используем Redis для сессий
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'session'

# Настройки для кэширования в приложении
CACHE_MIDDLEWARE_SECONDS = 600  # 10 минут для кэширования middleware
CACHE_MIDDLEWARE_KEY_PREFIX = 'purchasing'

# Настройки для кэширования Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # База данных 0 для Celery
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Настройки медиафайлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки изображений
IMAGE_UPLOAD_MAX_SIZE = 5 * 1024 * 1024  # 5MB
IMAGE_UPLOAD_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp']

# Размеры миниатюр
THUMBNAIL_SIZES = {
    'avatar': {
        'small': (50, 50),
        'medium': (150, 150),
        'large': (300, 300),
    },
    'product': {
        'thumbnail': (150, 150),
        'small': (300, 300),
        'medium': (600, 600),
        'large': (1200, 1200),
    }
}

# Оптимизация изображений
IMAGE_OPTIMIZATION = {
    'quality': 85,  # Качество JPEG
    'progressive': True,  # Прогрессивные JPEG
    'optimize': True,  # Оптимизация PNG
}