"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rbud4tf*o7%b8-q8o1r3f4zjtr_%!xk5z&o6e!wlh00b$0t%6d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jet',
    'jet.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rest_passwordreset',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular', 
    'celery',
    'backend.apps.BackendConfig',
    'django_cleanup.apps.CleanupConfig',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware', 
    
     # Custom middleware
    # 'api.middleware.SentryMiddleware',
    # 'api.middleware.APIErrorMiddleware',
    # 'api.middleware.QueryCountMiddleware',
]

ROOT_URLCONF = 'orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orders.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True
DATE_INPUT_FORMATS =  ['%d-%m-%Y', ]
DATE_FORMAT = 'd-m-Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL="backend.User"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',          # 100 запросов в час для анонимов
        'user': '1000/hour',         # 1000 запросов в час для пользователей
        'login': '5/minute',         # 5 запросов в минуту для входа
        'register': '10/hour',       # 10 запросов в час для регистрации
        'product_list': '60/minute', # 60 запросов в минуту для списка товаров
        'order_create': '20/hour',   # 20 запросов в час для создания заказов
    },
       
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',   
    
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Orders API',
    'DESCRIPTION': '''
    API для автоматизации закупок в розничной сети.
    
    ## Основные возможности
    
    - **Регистрация и аутентификация** пользователей (клиентов и поставщиков)
    - **Управление товарами** - создание, редактирование, импорт из разных форматов
    - **Оформление заказов** - заказы с товарами от разных поставщиков
    - **Управление заказами** - подтверждение, отмена, статистика
    - **Импорт товаров** - поддержка CSV, JSON, YAML форматов
    
    ## Аутентификация
    
    Для доступа к защищённым эндпоинтам требуется JWT токен.
    
    1. Получите токен: `POST /api/token/`
    2. Используйте в заголовке: `Authorization: Bearer <access_token>`
    
    ## Типы пользователей
    
    - **Клиент (client)** - делает закупки по каталогу
    - **Поставщик (supplier)** - управляет товарами и обрабатывает заказы
    
    ## Контакты
    
    - **Поддержка**: support@orders.com
    - **Версия API**: 1.0.0
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    
    # Настройки схемы
    'SCHEMA_PATH_PREFIX': r'/api/',
    
    # Кастомизация типов
    'ENUM_NAME_OVERRIDES': {
        'UserTypeEnum': 'backend.models.User.USER_TYPE_CHOICES',
        'OrderStatusEnum': 'backend.models.Order.STATUS_CHOICES',
    },
    
    # Скрыть некоторые поля из документации
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
}

# Redis Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # База данных 1 для кэша
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PARSER_CLASS': 'redis.connection.HiredisParser',  # Опционально, для ускорения
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            }
        },
        'KEY_PREFIX': 'orders',  # Префикс для всех ключей
        'TIMEOUT': 60 * 15,  # 15 минут по умолчанию
    },
    'session': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',  # База данных 2 для сессий
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'session',
    }
}

# Используем Redis для сессий
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'session'

# Настройки для кэширования в приложении
CACHE_MIDDLEWARE_SECONDS = 600  # 10 минут для кэширования middleware
CACHE_MIDDLEWARE_KEY_PREFIX = 'purchasing'

# Настройки для кэширования Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # База данных 0 для Celery
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Настройки медиафайлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки изображений
IMAGE_UPLOAD_MAX_SIZE = 5 * 1024 * 1024  # 5MB
IMAGE_UPLOAD_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp']

# Размеры миниатюр
THUMBNAIL_SIZES = {
    'avatar': {
        'small': (50, 50),
        'medium': (150, 150),
        'large': (300, 300),
    },
    'product': {
        'thumbnail': (150, 150),
        'small': (300, 300),
        'medium': (600, 600),
        'large': (1200, 1200),
    }
}

# Оптимизация изображений
IMAGE_OPTIMIZATION = {
    'quality': 85,  # Качество JPEG
    'progressive': True,  # Прогрессивные JPEG
    'optimize': True,  # Оптимизация PNG
}

# Настройки JET
JET_DEFAULT_THEME = 'default'  # 'default', 'green', 'light-green', 'light-violet', 'light-blue', 'light-gray'
JET_SIDE_MENU_COMPACT = False  # Компактное меню
JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultIndexDashboard'
JET_APP_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultAppIndexDashboard'

# Темы
JET_THEMES = [
    {
        'theme': 'default',  # тема по умолчанию
        'color': '#47bac1',  # цвет кнопки в меню пользователя
        'title': 'Default'
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

# Настройки бокового меню
JET_SIDE_MENU_ITEMS = [
    {
        'label': 'Пользователи и права',
        'app_label': 'auth',
        'items': [
            {'name': 'auth.user'},
            {'name': 'auth.group'},
            {'name': 'api.user'},
        ]
    },
    {
        'label': 'Закупки',
        'items': [
            {'name': 'api.supplier'},
            {'name': 'api.product'},
            {'name': 'api.productimage'},
            {'name': 'api.order'},
            {'name': 'api.orderitem'},
        ]
    },
    {
        'label': 'Каталог',
        'items': [
            {'name': 'api.category'},
            {'name': 'api.attribute'},
            {'name': 'api.productattribute'},
        ]
    },
    {
        'label': 'Логи и статистика',
        'items': [
            {'name': 'api.priceupdatelog'},
            {'name': 'admin.logentry'},
        ]
    },
]

# Настройки главной страницы
JET_INDEX_DASHBOARD_ITEMS = [
    {
        'label': 'Статистика',
        'items': [
            {
                'label': 'Заказы',
                'model': 'api.order',
                'children': [
                    {
                        'label': 'Новые заказы',
                        'model': 'api.order',
                        'query': {'status': 'pending'},
                    },
                    {
                        'label': 'Подтверждённые',
                        'model': 'api.order',
                        'query': {'status': 'confirmed'},
                    },
                ]
            },
            {
                'label': 'Товары',
                'model': 'api.product',
                'children': [
                    {
                        'label': 'Активные товары',
                        'model': 'api.product',
                        'query': {'is_active': True},
                    },
                    {
                        'label': 'Товары без изображений',
                        'model': 'api.product',
                        'query': {'image__isnull': True},
                    },
                ]
            },
        ]
    },
]

# Дополнительные настройки
JET_CHANGE_FORM_SIBLING_LINKS = True  # Ссылки на соседние записи
JET_SHOW_REMAINING_APPS = True  # Показывать остальные приложения
JET_SHOW_REMAINING_APPS_TO_SUPERUSERS = True

SENTRY_DSN = os.environ.get('SENTRY_DSN', 'https://your-sentry-dsn@sentry.io/123456')
SENTRY_ENVIRONMENT = os.environ.get('SENTRY_ENVIRONMENT', 'development')
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', 0.1))

# Инициализация Sentry
def before_send_filter(event, hint):
    """Фильтрация событий перед отправкой в Sentry"""
    # Игнорируем 404 и другие не критичные ошибки
    if 'exception' in event:
        exc_type = event['exception']['values'][0]['type']
        if exc_type in ['Http404', 'PermissionDenied', 'KeyboardInterrupt']:
            return None  # Не отправляем в Sentry
    return event

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
        RedisIntegration(),
        LoggingIntegration(
            level=logging.INFO,
            event_level=logging.ERROR
        ),
    ],
    environment=SENTRY_ENVIRONMENT,
    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    send_default_pii=True,  # ВНИМАНИЕ: в продакшене установите False!
    max_request_body_size='always',  
    before_send=before_send_filter,  # Фильтрация вместо ignore_errors
)

# Установка глобальных тегов 
if SENTRY_DSN:
    sentry_sdk.set_tag("project", "orders")
    sentry_sdk.set_tag("service", "backend")
    
# Настройки логирования для интеграции с Sentry
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'sentry': {
            'level': 'ERROR',  # Отправлять только ошибки в Sentry
            'class': 'sentry_sdk.integrations.logging.EventHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'application.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'sentry', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'sentry'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'sentry'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Только ошибки базы данных
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'sentry', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'sentry'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Настройки социальной аутентификации
AUTHENTICATION_BACKENDS = (
    # Социальные бэкенды
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.vk.VKOAuth2',
    'social_core.backends.yandex.YandexOAuth2',
    
    # Стандартная аутентификация Django
    'django.contrib.auth.backends.ModelBackend',
)

# URL для перенаправления после аутентификации
LOGIN_URL = '/api/auth/login/'
LOGIN_REDIRECT_URL = '/api/users/me/'
LOGOUT_REDIRECT_URL = '/'

# Настройки социальных провайдеров (используйте переменные окружения!)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

SOCIAL_AUTH_GITHUB_KEY = os.environ.get('GITHUB_CLIENT_ID', '')
SOCIAL_AUTH_GITHUB_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

SOCIAL_AUTH_VK_OAUTH2_KEY = os.environ.get('VK_APP_ID', '')
SOCIAL_AUTH_VK_OAUTH2_SECRET = os.environ.get('VK_APP_SECRET', '')
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']

SOCIAL_AUTH_YANDEX_OAUTH2_KEY = os.environ.get('YANDEX_CLIENT_ID', '')
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = os.environ.get('YANDEX_CLIENT_SECRET', '')

# Настройки безопасности
SOCIAL_AUTH_LOGIN_ERROR_URL = '/api/auth/error/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/api/users/me/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/api/users/me/'

# Создавать пользователей автоматически
SOCIAL_AUTH_USER_MODEL = 'backend.User'
SOCIAL_AUTH_USERNAME_IS_FULL_NAME = False
SOCIAL_AUTH_SLUGIFY_USERNAMES = True
SOCIAL_AUTH_CLEAN_USERNAMES = True

# Разрешить только определённые домены
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['example.com']
SOCIAL_AUTH_FACEBOOK_WHITELISTED_DOMAINS = ['example.com']

# Защита от атак
SOCIAL_AUTH_REDIRECT_IS_HTTPS = not DEBUG  # В продакшене только HTTPS
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']
SOCIAL_AUTH_INACTIVE_USER_URL = '/api/auth/inactive/'

# Кастомизация создания пользователей
SOCIAL_AUTH_PIPELINE = (
    # Получение социального аккаунта
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    
    # Получение данных пользователя
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    
    # Создание пользователя
    'social_core.pipeline.user.create_user',
    
    # Создание профиля пользователя в нашей системе
    'api.pipeline.create_user_profile',
    
    # Сохранение социального аккаунта
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    
    # Обновление данных пользователя
    'social_core.pipeline.user.user_details',
    
    # Генерация JWT токена
    'api.pipeline.generate_jwt_token',
)

# Настройки для безопасности
SOCIAL_AUTH_STRATEGY = 'social_django.strategy.DjangoStrategy'
SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'

# Ограничение попыток входа
SOCIAL_AUTH_LOGIN_RATE_LIMIT = 10  # 10 попыток в минуту
SOCIAL_AUTH_LOGIN_RATE_LIMIT_PERIOD = 60

# Валидация состояния
SOCIAL_AUTH_STATE_PARAMETER = True
SOCIAL_AUTH_NONCE_PARAMETER = True

# Защита от подделки запросов
SOCIAL_AUTH_REDIRECT_STATE = True